// eslint-disable-next-line camelcase
import { Fira_Code, Inter } from 'next/font/google'

import { FileProvider } from '@/context/File'
import { KeysProvider } from '@/context/Keys'

import './globals.css'

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--fira-code-font',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--inter-font',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${firaCode.variable} ${inter.variable} bg-space-cadet`}
    >
      <body className="bg-none bg-space-cadet">
        <KeysProvider>
          <FileProvider>{children}</FileProvider>
        </KeysProvider>
      </body>
    </html>
  )
}
